package constants

// ==================== Custom status codes (string) ====================
const (
	StatusCodeServiceSuccess             = "20001"
	StatusCodeDeleteSuccess              = "20201"
	StatusCodeBadRequest                 = "40000"
	StatusCodeInvalidCredentials         = "40001"
	StatusCodeErrorBindingBody           = "40002"
	StatusCodeInvalidTransaction         = "40003"
	StatusCodePrimaryKeyRequired         = "40004"
	StatusCodeModelValueRequired         = "40005"
	StatusCodeUnsupportedDriver          = "40006"
	StatusCodeRegistered                 = "40007"
	StatusCodeInvalidField               = "40008"
	StatusCodeInvalidData                = "40009"
	StatusCodeInvalidDB                  = "40010"
	StatusCodeInvalidValue               = "40011"
	StatusCodeNotImplemented             = "40012"
	StatusCodeMissingWhereClause         = "40013"
	StatusCodeUnsupportedRelation        = "40014"
	StatusCodeEmptySlice                 = "40015"
	StatusCodeDryRunUnsupported          = "40016"
	StatusCodeInvalidValueLength         = "40017"
	StatusCodePreloadNotAllowed          = "40018"
	StatusCodeValidationError            = "40019"
	StatusCodeIDsNotReadable             = "40020"
	StatusCodeNotAuthorizedNoHeader      = "40101"
	StatusCodeNotAuthorized              = "40102"
	StatusCodeRouteNotFound              = "40401"
	StatusCodeRecordNotFound             = "40402"
	StatusCodeDependencyNotFound         = "40403"
	StatusCodeIDNotFound                 = "40404"
	StatusCodeNotAcceptableNoAccept      = "40601"
	StatusCodeNotAcceptableNoContentType = "40602"
	StatusCodeInternalServerError        = "50001"
	StatusCodeFailedToDecodeValue        = "50011"
)
